### ISSUE TITLE
train_rl.py的问题

### ISSUE THREAD

**Issue by czhxiaohuihui** [DuJiajun1994/ImageCaptionGAN#1]
Traceback (most recent call last):
  File "/home/code/ImageCaption_GAN/train_rl.py", line 152, in <module>
    rl.train()
  File "/home/code/ImageCaption_GAN/train_rl.py", line 35, in train
    self._train_rl()
  File "/home/code/ImageCaption_GAN/train_rl.py", line 65, in _train_rl
    loss, reward = self._rl_core1(data)
  File "/home/code/ImageCaption_GAN/train_rl.py", line 94, in _rl_core1
    reward = self._get_reward(data, seqs)
  File "/home/code/ImageCaption_GAN/train_rl.py", line 75, in _get_reward
    scores = self.cider.get_scores(seqs.cpu().numpy(), data['images'].cpu().numpy())
  File "/home/code/ImageCaption_GAN/cider.py", line 18, in get_scores
    _, scores = self.cider.compute_score(gts, res)
  File "cider/pyciderevalcap/ciderD/ciderD.py", line 48, in compute_score
    (score, scores) = cider_scorer.compute_score(self._df)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 199, in compute_score
    score = self.compute_cider(df_mode)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 173, in compute_cider
    vec, norm, length = counts2vec(test)
  File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 122, in counts2vec
    df = np.log(max(1.0, self.document_frequency[ngram]))
KeyError: ('0',)
老哥，运行train_rl.py的时候会报这个错，是咋回事？

**Comment by czhxiaohuihui** [comment]
> Traceback (most recent call last):
> File "/home/code/ImageCaption_GAN/train_rl.py", line 152, in
> rl.train()
> File "/home/code/ImageCaption_GAN/train_rl.py", line 35, in train
> self._train_rl()
> File "/home/code/ImageCaption_GAN/train_rl.py", line 65, in _train_rl
> loss, reward = self._rl_core1(data)
> File "/home/code/ImageCaption_GAN/train_rl.py", line 94, in _rl_core1
> reward = self._get_reward(data, seqs)
> File "/home/code/ImageCaption_GAN/train_rl.py", line 75, in _get_reward
> scores = self.cider.get_scores(seqs.cpu().numpy(), data['images'].cpu().numpy())
> File "/home/code/ImageCaption_GAN/cider.py", line 18, in get_scores
> _, scores = self.cider.compute_score(gts, res)
> File "cider/pyciderevalcap/ciderD/ciderD.py", line 48, in compute_score
> (score, scores) = cider_scorer.compute_score(self._df)
> File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 199, in compute_score
> score = self.compute_cider(df_mode)
> File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 173, in compute_cider
> vec, norm, length = counts2vec(test)
> File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 122, in counts2vec
> df = np.log(max(1.0, self.document_frequency[ngram]))
> KeyError: ('0',)
> 老哥，运行train_rl.py的时候会报这个错，是咋回事？

换了另一个cider文件就ok了。

**Comment by gorgeousyouth** [comment]
> > Traceback (most recent call last):
> > File "/home/code/ImageCaption_GAN/train_rl.py", line 152, in
> > rl.train()
> > File "/home/code/ImageCaption_GAN/train_rl.py", line 35, in train
> > self._train_rl()
> > File "/home/code/ImageCaption_GAN/train_rl.py", line 65, in _train_rl
> > loss, reward = self._rl_core1(data)
> > File "/home/code/ImageCaption_GAN/train_rl.py", line 94, in _rl_core1
> > reward = self._get_reward(data, seqs)
> > File "/home/code/ImageCaption_GAN/train_rl.py", line 75, in _get_reward
> > scores = self.cider.get_scores(seqs.cpu().numpy(), data['images'].cpu().numpy())
> > File "/home/code/ImageCaption_GAN/cider.py", line 18, in get_scores
> > _, scores = self.cider.compute_score(gts, res)
> > File "cider/pyciderevalcap/ciderD/ciderD.py", line 48, in compute_score
> > (score, scores) = cider_scorer.compute_score(self._df)
> > File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 199, in compute_score
> > score = self.compute_cider(df_mode)
> > File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 173, in compute_cider
> > vec, norm, length = counts2vec(test)
> > File "cider/pyciderevalcap/ciderD/ciderD_scorer.py", line 122, in counts2vec
> > df = np.log(max(1.0, self.document_frequency[ngram]))
> > KeyError: ('0',)
> > 老哥，运行train_rl.py的时候会报这个错，是咋回事？
> 
> 换了另一个cider文件就ok了。

请问一下你达到论文的效果了吗？我用了你的代码复现出来效果很差。
